config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :collections, only: [:show]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :show, :destroy]


  get 'pages/index'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :activity_collection, dependent: :destroy
	has_many :activities, through: :activity_collection, dependent: :destroy
	mount_uploader :photo, ImageUploader

	has_many :user_collection
	has_many :users, through: :user_collection

	belongs_to :user, class_name: 'User', foreign_key: :owner_id
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
	authorize_resource
  def show
  	@collection = Collection.find(params[:id])

  	if UserCollection.where(user_id: current_user.id, collection_id: params[:id]) != []
  		@registrada = true
  	else
  		@registrada = false
  	end

  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/show.html.erb
<div id="fondo-act" class="fondo_activity">

	<div class="cuadro_centro_act">
		<div class="row">
			<div class="col-6">
				<h3><%= @collection.name %></h3><br>
				<img src="<%= @collection.photo.normal %>">
			</div>

			<div class="col-6">
				<% if @registrada %>
					<%= link_to 'Dejar de seguir esta Colección', user_collection_path(@collection.id), method: :delete, :class => 'btn btn-info'%>
				<% else %>
					<%= link_to 'Seguir esta Colección', user_collections_path(:collection_id => @collection.id), method: :post, :class => 'btn btn-info'%>
				<% end %>
				<br><br>
				<h5>Actividades en esta colección:</h5>
				<ol>
					<% @collection.activities.each do |activity| %>
						<li><h6><%= link_to activity.name, activity_path(activity) %>
							<% current_user.activities.each do |my_act| %>
								<% if my_act.id == activity.id %>
									<i>actividad realizada</i>
								<% end %>
							<% end %>

						</h6></li>
					<% end %>
				</ol>

			</div>
			
			<br>

		</div>
		

		<img src="<%= @collection.photo %>" id="lo" style="display: none">
	</div>
</div>

<script>
		
		$("#fondo-act").backstretch(document.getElementById("lo").src)
		
		

</script>