config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :collections, only: [:show]
  resources :user_collections, only: [:create, :destroy]
  resources :user, only: [:show]
  resources :activities, only: [:create, :new, :show, :edit, :update]
  resources :user_activities, only: [:create, :edit, :update, :destroy]
  resources :contacts, only: [:create, :destroy]
  resources :promote_activities, only: [:new, :create, :show, :destroy]


  get 'pages/index'
  get 'pages/politica'

  get 'user_calendar/:id', to: 'user#user_calendar', as: 'user_calendar'
  patch 'edit_calendar/:activity_id', to: 'user#update_calendar', as: 'update_user_calendar'
  
 

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        :omniauth_callbacks => "user/omniauth_callbacks",
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activity, dependent: :destroy
	has_many :users, through: :user_activity, dependent: :destroy

	belongs_to :category, optional: true
	has_many :promote_activity, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id

	mount_uploader :photo, ImageUploader

	has_many :activity_collection, dependent: :destroy
	has_many :collections, through: :activity_collection, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	authorize_resource

	def show
		@activity = Activity.find(params[:id])
		if user_signed_in?
			if UserActivity.where(user_id: current_user.id,activity_id: @activity.id) != []
				@registrada = true
				@user_activity = UserActivity.where(user_id: current_user.id,activity_id: @activity.id).first
			else
				@registrada = false
			end
		end
	end

	def new
		@activity = Activity.new
		@categories = Category.all
	end

	def create
		@activity = Activity.new
		@activity.name = params[:activity][:name]
		@activity.category_id = params[:activity][:category_id]
		@activity.photo = params[:activity][:photo]
		@activity.remote_photo_url = params[:activity][:remote_photo_url]
		@activity.owner_id = current_user.id
		@activity.save
		redirect_to root_path, notice: 'la actividad fue creada. Puede ingresarla a su registro si lo desea'
	end

	def edit	
		@activity = Activity.find(params[:id])
		@categories = Category.all
		
	end

	def update
		@activity = Activity.find(params[:id])
		@activity.update(name: params[:activity][:name])
		@activity.update(author: params[:activity][:author])
		@activity.update(category_id: params[:activity][:category_id])
		@activity.update(photo: params[:activity][:photo])
		@activity.update(remote_photo_url: params[:activity][:remote_photo_url])
    	redirect_to user_path(current_user)
	end

	
	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h2>Editar Actividad </h2>
<br>
<% if user_signed_in? %>
	<%= form_with model: @activity, url: activity_path(@activity), method: :patch, local: true do |f| %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>	<br>

		<%= f.label :author %>
		<%= f.text_field :author %>	<br>

		<%= f.label :category %>
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %> <br>


	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

			

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

app/views/activities/new.html.erb
<h2>Crear nueva actividad </h2>
<br>

<% if user_signed_in? %>
	<%= form_with model: @activity, url: activities_path, method: :post, local: true do |f| %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>	<br>

		<%= f.label :autor %>
		<%= f.text_field :author %>	<br>

		<%= f.label :categoría %>
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %><br>


	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

			

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

app/views/activities/show.html.erb
<div id="fondo-act" class="fondo_activity">

	<div class="cuadro_centro_act">
		<div class="row">
			<div class="col-6">
				<h3><%= @activity.name %></h3><br>
				<img src="<%= @activity.photo.normal %>">
			</div>
			<div class="col-6 boton">
				<% if user_signed_in? %>
					<% if @registrada %>
					<%= link_to 'Borrar registro de actividad', user_activity_path(@user_activity.id), method: :delete, :class => 'btn btn-danger' %>
					<% else %>
						<%= link_to 'Registrar actividad', user_activities_path(:activity_id=> @activity.id, :status=> 'realizada',:user_id => current_user.id), method: :post, :class => 'btn btn-danger' %>
						<%= link_to 'Marcar como por realizar', user_activities_path(:activity_id=> @activity.id, :status=> 'por_hacer',:user_id => current_user.id), method: :post, :class => 'btn btn-warning' %>
					<% end %>
				<% end %>
				<br><br>
				<h5>Colecciones a la que pertence la actividad:</h5>
				<ul>
					<% @activity.collections.each do |collection| %>
						<li><h6><%= link_to collection.name, collection_path(collection) %></h6></li>
					<% end %>
				</ul>
			</div>
			<br>

		</div>
		<br>
		<% if can?(:edit, @activity) %>
			<%= link_to 'Editar actividad', edit_activity_path(@activity.id), :class => 'btn btn-info' %>
		<% end %>

		<img src="<%= @activity.photo %>" id="lo" style="display: none">
	</div>
</div>

<script>
		
		$("#fondo-act").backstretch(document.getElementById("lo").src)
		
		

</script>